# Generated by Django 5.2.1 on 2025-06-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastomensual',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='Doctor responsable de este gasto.', on_delete=django.db.models.deletion.PROTECT, related_name='gastos_mensuales', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
    ]
