# Generated by Django 5.2.1 on 2025-06-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gastomensual_doctor'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='Doctor asignado a la cita.', on_delete=django.db.models.deletion.PROTECT, related_name='citas_medicas', to='core.doctor', verbose_name='Doctor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('doctor', 'fecha', 'hora_cita')},
        ),
    ]
